using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyTodos.SharedKernel.Abstractions;

namespace MyTodos.BuildingBlocks.Infrastructure.Persistence.Abstractions.Configs;

/// <summary>
/// EF Core configuration for aggregate roots with GUID identifiers.
/// GUIDs are never generated by the database - the application must provide them.
/// Use this for aggregate roots in distributed systems or when you need client-generated IDs.
/// </summary>
public class AggregateRootWithGuidIdConfig<TEntity> : EntityWithGuidIdConfig<TEntity>
    where TEntity : AggregateRoot<Guid>
{
    public override void Configure(EntityTypeBuilder<TEntity> builder)
    {
        base.Configure(builder);

        builder.Ignore(e => e.DomainEvents);
    }
}
