using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyTodos.SharedKernel.Abstractions;

namespace MyTodos.BuildingBlocks.Infrastructure.Persistence.Abstractions.Configs;

/// <summary>
/// EF Core configuration for aggregate roots with string identifiers.
/// String IDs are never generated by the database - the application must provide them.
/// Abstract class requires derived classes to specify IdMaxLength based on domain requirements.
/// Examples: OrderNumber (50), Email (320), TenantCode (20).
/// </summary>
public abstract class AggregateRootWithStringIdConfig<TEntity> : EntityWithStringIdConfig<TEntity>
    where TEntity : AggregateRoot<string>
{
    public override void Configure(EntityTypeBuilder<TEntity> builder)
    {
        base.Configure(builder);

        builder.Ignore(e => e.DomainEvents);
    }
}
