using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyTodos.SharedKernel.Abstractions;

namespace MyTodos.BuildingBlocks.Infrastructure.Persistence.Abstractions.Configs;

/// <summary>
/// EF Core configuration for aggregate roots with auto-generated integer identifiers.
/// Database generates IDs automatically (IDENTITY column in SQL Server).
/// Use this for simple aggregate roots where database-generated sequential IDs are appropriate.
/// </summary>
public class AggregateRootWithIntIdAutoGeneratedConfig<TEntity> : EntityWithIntIdAutoGeneratedConfig<TEntity>
    where TEntity : AggregateRoot<int>
{
    public override void Configure(EntityTypeBuilder<TEntity> builder)
    {
        base.Configure(builder);

        builder.Ignore(e => e.DomainEvents);
    }
}
