using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyTodos.SharedKernel.Abstractions;

namespace MyTodos.BuildingBlocks.Infrastructure.Persistence.Abstractions.Configs;

/// <summary>
/// EF Core configuration for entities with GUID identifiers.
/// GUIDs are never generated by the database - the application must provide them.
/// Use this for entities where you need client-generated IDs or distributed systems.
/// </summary>
public class EntityWithGuidIdConfig<TEntity> : EntityConfig<TEntity, Guid>
    where TEntity : Entity<Guid>
{
    public override void Configure(EntityTypeBuilder<TEntity> builder)
    {
        base.Configure(builder);

        builder
            .Property(a => a.Id)
            .ValueGeneratedNever();
    }
}
