using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyTodos.SharedKernel.Abstractions;

namespace MyTodos.BuildingBlocks.Infrastructure.Persistence.Abstractions.Configs;

/// <summary>
/// EF Core configuration for entities with string identifiers.
/// String IDs are never generated by the database - the application must provide them.
/// Abstract class requires derived classes to specify IdMaxLength based on domain requirements.
/// Examples: OrderNumber (50), Email (320), URL (2000).
/// </summary>
public abstract class EntityWithStringIdConfig<TEntity> : EntityConfig<TEntity, string>
    where TEntity : Entity<string>
{
    protected abstract int IdMaxLength { get; }

    public override void Configure(EntityTypeBuilder<TEntity> builder)
    {
        base.Configure(builder);

        builder
            .Property(e => e.Id)
            .HasMaxLength(IdMaxLength)
            .ValueGeneratedNever();
    }
}
