using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using MyTodos.SharedKernel.Abstractions;

namespace MyTodos.BuildingBlocks.Infrastructure.Persistence.Abstractions.Configs;

/// <summary>
/// EF Core configuration for entities with auto-generated integer identifiers.
/// Database generates IDs automatically (IDENTITY column in SQL Server).
/// Use this for simple entities where database-generated sequential IDs are appropriate.
/// </summary>
public class EntityWithIntIdAutoGeneratedConfig<TEntity> : EntityConfig<TEntity, int>
    where TEntity : Entity<int>
{
    public override void Configure(EntityTypeBuilder<TEntity> builder)
    {
        base.Configure(builder);
    }
}
